version: "3.8"

services:
  backend:
    container_name: fasttalk-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: ${MONGO_URI}
      REDIS_URI: ${REDIS_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_LIFETIME: ${JWT_LIFETIME}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      PORT: ${BACKEND_PORT_NUMBER}
      FRONTEND_URL: ${FRONTEND_URL}
    depends_on:
      - mongodb
      - redis
    restart: unless-stopped
    networks:
      - fasttalk-network

  frontend:
    container_name: fasttalk-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    ports:
      - "80:80"
    environment:
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - fasttalk-network

  mongodb:
    image: mongo:8
    container_name: fasttalk-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - fasttalk-network
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 10

  mongo-express:
    image: mongo-express:latest
    container_name: fasttalk-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - fasttalk-network

  redis:
    image: redis:7
    container_name: fasttalk-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'
    networks:
      - fasttalk-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  mongodb_data:
  redis_data:


networks:
  fasttalk-network:
    driver: bridge
